server:
  port: 9001
  servlet:
    context-path: /first

spring:
  application:
    name: lfy-first

eureka:
  instance:
    hostname: localhost
    # 每隔5s发送一次心跳
    lease-renewal-interval-in-seconds: 5
    # 告知服务端10s还未收到心跳的话，就将该服务移除列表
    lease-expiration-duration-in-seconds: 10
  client:
    #表示是否注册Eureka服务器,因为自身作为服务注册中心，所以为false
    register-with-eureka: true
    #从Eureka服务端获取注册信息的时间间隔，单位：秒
    registry-fetch-interval-seconds: 30
    #是否从Eureka服务端获取注册信息
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin@${eureka.instance.hostname}:8000/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    #清理间隔，一旦服务down掉，则默认60秒（此处2秒）才注销该服务
    eviction-interval-timer-in-ms: 2000
    #Eureka的自我保护机制
    enable-replicated-request-compression: false

# Feign
feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
      cors:
        allowed-origins: '*'
        allowed-methods: '*'
  endpoint:
    health:
      show-details: always