server:
  port: 9000

spring:
  application:
    name: lfy-zuul

eureka:
  instance:
    hostname: localhost
  client:
    #表示是否注册Eureka服务器,因为自身作为服务注册中心，所以为false
    register-with-eureka: true
    #从Eureka服务端获取注册信息的时间间隔，单位：秒
    registry-fetch-interval-seconds: 30
    #是否从Eureka服务端获取注册信息
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin@${eureka.instance.hostname}:8000/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    #清理间隔，一旦服务down掉，则默认60秒（此处2秒）才注销该服务
    eviction-interval-timer-in-ms: 2000
    #Eureka的自我保护机制
    enable-replicated-request-compression: false


zuul:
  set-content-length: true
  add-host-header: true
  ignored-services: '*' # 忽略所有为配置的service
  host:
    connect-timeout-millis: 4000
    socket-timeout-millis: 2000
  # 路由配置
  routes:
    lfy-first: #自定义名称
      serviceId: lfy-first
      path: /first/**
      stripPrefix: false
    lfy-second:
      serviceId: lfy-second
      path: /second/**
      stripPrefix: false
