server:
  port: 8888
  servlet:
    context-path: /admin

spring:
  application:
    name: lfy-admin
  security:
    user:
      name: admin
      password: admin

eureka:
  instance:
    hostname: localhost
  client:
    #表示是否注册Eureka服务器,因为自身作为服务注册中心，所以为false
    register-with-eureka: true
    #从Eureka服务端获取注册信息的时间间隔，单位：秒
    registry-fetch-interval-seconds: 30
    #是否从Eureka服务端获取注册信息
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin@${eureka.instance.hostname}:8000/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    #清理间隔，一旦服务down掉，则默认60秒（此处2秒）才注销该服务
    eviction-interval-timer-in-ms: 2000
    #Eureka的自我保护机制
    enable-replicated-request-compression: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
      cors:
        allowed-origins: '*'
        allowed-methods: '*'
  endpoint:
    info:
      enabled: true
    health:
      show-details: always
